### ISSUE TITLE
Cursor doesn't update (in Normal mode) when using vim-wordmotion

### ISSUE THREAD

**Issue by xkocahete** [mickael-menu/ShadowVim#50]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [ ] I reproduced the issue with an empty Neovim configuration (`init.vim` or `init.lua`)
- [X] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

The cursor is not updated, but the motion happens, i.e. any further interactions would take place as if the cursor were it was supposed to be. The issue does not happen in Visual mode.

### How to reproduce?

1. Open any swift file
2. Go to normal mode
3. Find a word benefiting from the vim plugin,  such as "CamelCaseACRONYMWords_underscore1234"
4. Move within the word with word motions: w, b, e
5. Cursor doesn't redraw

### Neovim configuration

```viml
call plug#begin('~/.local/share/nvim/plugged')
Plug 'chaoren/vim-wordmotion'
call plug#end()
```

### Environment

```bash
ShadowVim 0.2.0 (3)

$ sw_vers -productVersion
13.3.1

$ uname -m
arm64

$ whereis nvim
nvim: /opt/homebrew/bin/nvim /opt/homebrew/share/man/man1/nvim.1

$ nvim --version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"

Run :checkhealth for more info

$ xcodebuild -version
Xcode 14.3
Build version 14E222b

$ defaults read -app Xcode KeyBindingsMode
Default

$ defaults read -app Xcode DVTTextAutoCloseBlockComment
exit status: 1

$ defaults read -app Xcode DVTTextAutoInsertCloseBrace
exit status: 1

$ defaults read -app Xcode DVTTextEditorTrimTrailingWhitespace
0

$ defaults read -app Xcode DVTTextEnableTypeOverCompletions
1

$ defaults read -app Xcode DVTTextIndentCaseInC
0

$ defaults read -app Xcode DVTTextUsesSyntaxAwareIndenting
exit status: 1
```

**Comment by mickael-menu** [comment]
Thanks, I'm pushing a fix in `develop`.

The Nvim mode changed to `cmdline` when triggering `vim-wordmotion` movement, which was not considered when synchronizing the position. This caused the issue.

**Comment by xkocahete** [comment]
I wasn't able to verify the fix yet. Though building off `develop` works, I can't run the resulting `.app`. It may be related to using a different Bundle Identifier to get the code signed and macOS  not recognizing it in the already granted Accessibility permissions. Anyway, I will carve out some time to investigate this later. 

By the way, I'm having the same issue when using `%` in normal mode (to jump to the matching `([{}])`). Do you think your fix could have covered that case too?

Thank you!

**Comment by mickael-menu** [comment]
>  I can't run the resulting .app. It may be related to using a different Bundle Identifier to get the code signed and macOS not recognizing it in the already granted Accessibility permissions.

Ha yes, unfortunately a notarized app is considered like a whole different one from the manually built one. You need to remove ShadowVim in the list of permissions, before relaunching the app.

Alternatively, I notarized the build here: [ShadowVim.app.zip](https://github.com/mickael-menu/ShadowVim/files/11645647/ShadowVim.app.zip)

> By the way, I'm having the same issue when using % in normal mode (to jump to the matching ([{}])). Do you think your fix could have covered that case too?

It works for me so I guess so.
