### ISSUE TITLE
Jump to matching brace not displaying visually

### ISSUE THREAD

**Issue by colbymorrison** [mickael-menu/ShadowVim#53]
If I hit `%`, I expect to jump to the matching brace/paren. It looks like neovim is processing the command internally, but the cursor does not move when I hit `%`. By this I mean, if I press `%`, nothing happens visually. But if I press `%h`, the cursor does move to the left of the matching brace/paren. 

This is something the native XCode vim emulation gets correct.

XCode 14.41
Neovim 0.9.0
MacOS Ventura 13.0.1

**Comment by mickael-menu** [comment]
I cannot reproduce this issue. Can you reproduce it with an empty `init.vim`?

https://github.com/mickael-menu/ShadowVim/assets/58686775/ddefe966-51ea-4898-9b05-7e7cc7590584


Note that I fixed another issue that might have solved this if you're using plugins such as `vim-wordmotion`. See https://github.com/mickael-menu/ShadowVim/issues/50

Try with this build and see if that helps:
 https://github.com/mickael-menu/ShadowVim/files/11645647/ShadowVim.app.zip

**Comment by colbymorrison** [comment]
Switching to that build you linked fixed this issue! Thanks very much!
