### ISSUE TITLE
Passthrough the fn/international key

### ISSUE THREAD

**Issue by darvelo** [mickael-menu/ShadowVim#56]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [X] I reproduced the issue with an empty Neovim configuration (`init.vim` or `init.lua`)
- [x] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Any chance the fn/international key can be passed through? I speak two languages and I have macOS set to switch between them while using any app, but it seems ShadowVim is intercepting the keypress.

I see #33 but I don't think there's a keycode for just a single Fn keypress (not F1, F2, etc., just Fn), and searched but couldn't find how to map it in vim.

### How to reproduce?

1. Add another language and set macOS to use a fn keypress to switch between them.
2. Open ShadowVim and press the key.
3. Nothing happens

### Neovim configuration

```viml
Empty config
```

**Comment by superarts** [comment]
It will be a great chance!

**Comment by mickael-menu** [comment]
Hi @darvelo, thanks for reporting this issue. I adapted your findings in a new PR (https://github.com/mickael-menu/ShadowVim/pull/58) that also handles key combo with the <kbd>Fn</kbd> modifier, AFAIK they are not supported in Vim anyways.

**Comment by darvelo** [comment]
@mickael-menu Fantastic, thank you for providing a proper fix for this. 👏🏽
