### ISSUE TITLE
Xcode 15 support?

### ISSUE THREAD

**Issue by falcucci** [mickael-menu/ShadowVim#65]

**Comment by mickael-menu** [comment]
I'm using ShadowVim with Xcode 15.

**Comment by falcucci** [comment]
@mickael-menu thank you for letting me know :)

but unfortunately it doesn't works here, any tips for troubleshoot this?

I have compiled the project from source aswell but nothing changed, trying to see some logs to help.

**Comment by mickael-menu** [comment]
I recommend starting with an empty `init.vim` and add things progressively, as many nvim plugins can interfere with ShadowVim. [See these instructions](https://github.com/mickael-menu/ShadowVim?tab=readme-ov-file#neovim-configuration).

Try also running this in a terminal window, after opening ShadowVim and a source file in Xcode. If you see a blank screen, try hitting any key, I noticed that sometimes Neovim gets stuck without any feedback through their RPC API.

```sh
nvim --server /tmp/shadowvim.pipe --remote-ui
```

**Comment by mickael-menu** [comment]
As for logs, try changing this to `.trace`:

https://github.com/mickael-menu/ShadowVim/blob/a4fbea4c9322eb9c0db904808c0c54466605c133/Sources/ShadowVim/Container.swift#L34
