### ISSUE TITLE
Cursor is not visible against dark backgrounds

### ISSUE THREAD

**Issue by jonmindtrip** [mickael-menu/ShadowVim#66]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [X] I reproduced the issue with an empty Neovim configuration (`init.vim` or `init.lua`)
- [X] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

When shadowvim is enabled at the same time as a dark theme, the cursor is very difficult to see. I've tried changing the cursor style and color in Xcode > Settings > Themes, and also tried modifying the cursor appearance using "set guicursor" commands in init.vim, neither had any effect on the cursor appearance in Xcode.

### How to reproduce?

Xcode > Settings > Themes, select a dark theme. Note the cursor appearance is identical to when using a light theme. Solarized Dark in particular is almost exactly the same color as the cursor making it almost impossible to find the cursor in normal mode (see attachment). Insert mode the cursor is much brighter. 
![Screenshot 2024-05-16 at 11 39 06 AM](https://github.com/mickael-menu/ShadowVim/assets/169461461/73161dfb-1e25-44b7-b05d-b8d0d02ae6e0)

### Neovim configuration

```viml
n/a
```

### Environment

```bash
ShadowVim 0.2.1 (4)

$ sw_vers -productVersion
14.4

$ uname -m
arm64

$ whereis nvim
nvim: /opt/homebrew/bin/nvim /opt/homebrew/share/man/man1/nvim.1

$ nvim --version
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info

$ xcodebuild -version
exit status: 1

$ defaults read -app Xcode KeyBindingsMode
Default

$ defaults read -app Xcode DVTTextAutoCloseBlockComment
exit status: 1

$ defaults read -app Xcode DVTTextAutoInsertCloseBrace
exit status: 1

$ defaults read -app Xcode DVTTextEditorTrimTrailingWhitespace
exit status: 1

$ defaults read -app Xcode DVTTextEnableTypeOverCompletions
exit status: 1

$ defaults read -app Xcode DVTTextIndentCaseInC
exit status: 1

$ defaults read -app Xcode DVTTextUsesSyntaxAwareIndenting
exit status: 1
```

**Comment by mickael-menu** [comment]
You need to change the text selection color in Xcode's color scheme.

**Comment by jonmindtrip** [comment]
thanks - super helpful! Any way to stop empty lines from using the selection color across the full editor? (see attached)

![Screenshot 2024-05-16 at 12 14 05 PM](https://github.com/mickael-menu/ShadowVim/assets/169461461/9d743e0f-7445-45ef-8beb-62a2f092911a)

**Comment by mickael-menu** [comment]
Unfortunately not, it could show a simple insert cursor but I found it more confusing in practice.
